# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 22:09
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=colorfield.fields.ColorField(default='#96CFFF', max_length=10),
        ),
    ]
